---

- name: Set Login banner
  cisco.ios.ios_banner:
    banner: login
    multiline_delimiter: '%'
    text: | 

      #######################################################\n
      #                                                          #\n
        #   WARNING: Unauthorized access is strictly prohibited. #\n
        #   All connections are monitored and recorded.          #\n
        #   You have successfully entered this system.           #\n
      #                                                          #\n
      #######################################################\n
      |
    state: present 

